### ISSUE TITLE
Block characters on the Change log window

### ISSUE THREAD

**Issue by jjtriff** [KaOS-Community-Packages/sublime-text-dev#3]
Hi:

This is probably a gtk issue in general but when I open the Change log window the text is unreadable because all I can see are squares, like when you try to open something but the system can resolve the font file to show that text.

If I keep scrolling down some words appear: the ones with monospaced font, but only those I can read correctly.

Any solution??

Thanks in advanced

**Comment by raul338** [comment]
Its something to do with configuration of your system. Try with a new user in your system.

**Comment by jjtriff** [comment]
you are right. I've just installed Kaos in a VM and the default profile works ok in this matter with sublime.
i'll have to dig into the configs. thanks.

**Comment by ShalokShalom** [comment]
You might want to close this issue.
